version: '3'

services:
  mysql:
    image: 'mysql:8'
    container_name: 'mysql-container'
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=datab  # Replace with your desired database name
    ports:
      - "3306:3306"

  app:
    build: .  # Builds the application from the Dockerfile in the current directory
    container_name: 'app-container'
    depends_on:
      - mysql  # Ensures app starts after MySQL is ready
    ports:
      - "8081:8080"  # Example port mapping for your app (replace 80 with your app's port)